version: '3.9'
services:
  web:
    container_name: 'api'
    image: 'backendbase'
    build: 
      context: .
      dockerfile: ./BackEndBase.Api/Dockerfile
    ports:
      - '80:80'
    depends_on:
      - 'postgres'
    networks:
      - database-network  

  postgres:
    ports:
      - '5432:5432'
    container_name: postgresql-db
    environment:
      - POSTGRES_PASSWORD=Senha1234
    image: 'postgres'
    networks:
      - database-network

networks:
  database-network:
    driver: bridge